name: 'Fetch Metadata from Dependabot PRs'
description: 'Extract information from about the dependency being updated by a Dependabot-generated PR'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
outputs:
  dependency-name:
    description: 'The updated package name.'
  dependency-type:
    description: 'The type of dependency Dependabot has determined this to be, e.g. "direct:production".'
  update-type:
    description: 'The semvver change being made, e.g. "version-update:semver-major"'
runs:
  using: 'node12'
  main: 'dist/index.js'
