name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Read .nvmrc
      id: nvm
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.nvm.outputs.NVMRC }}

    - name: Install npm dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm test
